### ISSUE TITLE
As a user, I can view subjects with their name and description from the dashboard

### ISSUE THREAD

**Issue by wztech0192** [wztech0192/knowledge-hub#1]
![Image](https://github.com/wztech0192/knowledge-hub/assets/39068227/6b64ea96-59d5-4c1c-85ac-314d13d51084)

**Comment by Soumik29** [comment]
I will work on this issue now. I will create a branch for this issue and will start working on it

**Comment by Soumik29** [comment]
I will start working on this issue.

**Comment by Soumik29** [comment]
This issue has been resolved
