### ISSUE TITLE
As a user, I can click each subject to see its detail and topics

### ISSUE THREAD

**Issue by wztech0192** [wztech0192/knowledge-hub#2]
![Image](https://github.com/wztech0192/knowledge-hub/assets/39068227/963a54fe-e62a-4060-9b7c-29575f38291b)

**Comment by Soumik29** [comment]
I will start working on this issue now. 

I will create a new branch named subjectPage

**Comment by Soumik29** [comment]
Now as a user, I can click on each subject to see it's detail and it's topics. #2
