### ISSUE TITLE
As a user, I can view each subtopic pdf

### ISSUE THREAD

**Issue by wztech0192** [wztech0192/knowledge-hub#3]
I should be able to switch subtopics by using the subtopc dropdown and the prev/next buttons.

Use react-pdf.js library to render the pdf
https://www.npmjs.com/package/react-pdf

![Image](https://github.com/wztech0192/knowledge-hub/assets/39068227/ac427234-d1b5-4b6d-b820-c538b199f337)

**Comment by Soumik29** [comment]
I will create a feature3 branch and start working on it.
